[aws]
region = "us-east-1"
access_key_id = "test_key"
secret_access_key = "test_secret"

[[records]]
hosted_zone_id = "Z123456789ABC"
name = "test.example.com"
ttl = 300

[[records]]
hosted_zone_id = "Z987654321XYZ"
name = "home.example.com"
ttl = 600
