name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Nix cache
        uses: cachix/cachix-action@v12
        with:
          name: auto-dns
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true

      - name: Check flake
        run: nix flake check

      - name: Check formatting
        run: nix develop --command cargo fmt -- --check

      - name: Run clippy
        run: nix develop --command cargo clippy -- -D warnings

      - name: Run tests
        run: nix develop --command cargo test --verbose

      - name: Build with Nix
        run: nix build

      - name: Test binary
        run: ./result/bin/auto-dns --help
